# Generated by Django 5.0.6 on 2024-07-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_system', '0004_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
