# Generated by Django 5.0.6 on 2024-07-02 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_system', '0005_asset_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='asset_system.asset_class'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
