# Generated by Django 5.0.6 on 2024-07-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_system', '0007_asset_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='percent_dep',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
