# Generated by Django 5.0.6 on 2024-07-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_system', '0008_asset_percent_dep'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='Total_cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
