# Generated by Django 5.0.6 on 2024-07-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_system', '0010_alter_asset_assigned_to_alter_asset_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(max_length=250),
        ),
    ]
