# Generated by Django 5.0.4 on 2024-06-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('ST', 'Student'), ('CA', 'Career'), ('BU', 'Business')], default='ST', max_length=2),
        ),
    ]
