# Generated by Django 5.0.4 on 2024-06-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbn', '0002_document_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
