# Generated by Django 5.0.4 on 2024-06-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbn', '0004_alter_document_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='link',
        ),
    ]
