# Generated by Django 5.0.4 on 2024-06-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbn', '0005_youtubevideo_remove_document_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='category',
            field=models.CharField(choices=[('ST', 'Student'), ('CA', 'Career'), ('BU', 'Business')], default='ST', max_length=2),
        ),
    ]
