# Generated by Django 5.0.6 on 2024-07-05 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='team_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='follow_app.team_lead'),
        ),
        migrations.AlterField(
            model_name='member',
            name='team_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='follow_app.teammember'),
        ),
    ]
