# Generated by Django 5.0.6 on 2024-07-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_app', '0002_alter_member_team_lead_alter_member_team_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='house_position',
            field=models.CharField(default='non-house-member', max_length=50),
        ),
    ]
