# Generated by Django 5.0.6 on 2024-07-06 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_app', '0003_member_house_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='householdmember',
            name='position',
            field=models.CharField(choices=[('head', 'Household Head'), ('assistant', 'Household Head Assistance'), ('member', 'Household Member')], default='member', max_length=100),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_text', models.TextField()),
                ('date_filed', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('household_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='follow_app.householdmember')),
            ],
        ),
    ]
