# Generated by Django 5.0.6 on 2024-07-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_app', '0004_alter_householdmember_position_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_lead',
            name='department',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
