# Generated by Django 5.0.6 on 2024-07-09 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow_app', '0005_team_lead_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_lead',
            name='department',
        ),
    ]
