# Generated by Django 5.0.6 on 2024-07-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_app', '0006_remove_team_lead_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='team_lead',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='team_member',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
