# Generated by Django 5.0.6 on 2024-07-11 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_app', '0007_alter_member_team_lead_alter_member_team_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='head',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='household_head', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
