# Generated by Django 5.0.6 on 2024-07-11 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_app', '0009_remove_household_head'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TcgcHousehold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_name', models.CharField(max_length=255)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='households', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TcgcHouseholdMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('head', 'Household Head'), ('assistant', 'Household Head Assistant'), ('member', 'Household Member')], default='member', max_length=100)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='follow_app.tcgchousehold')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='follow_app.member')),
            ],
        ),
        migrations.AddField(
            model_name='tcgchousehold',
            name='members',
            field=models.ManyToManyField(through='follow_app.TcgcHouseholdMember', to='follow_app.member'),
        ),
    ]
