# Generated by Django 5.0.6 on 2024-07-11 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_app', '0010_tcgchousehold_tcgchouseholdmember_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcgchouseholdmember',
            name='household',
        ),
        migrations.RemoveField(
            model_name='tcgchouseholdmember',
            name='member',
        ),
        migrations.CreateModel(
            name='tcgc_Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_name', models.CharField(max_length=255)),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tcgc_HouseholdMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('head', 'Household Head'), ('assistant', 'Household Head Assistance'), ('member', 'Household Member')], default='member', max_length=100)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='follow_app.tcgc_household')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='follow_app.member')),
            ],
        ),
        migrations.AddField(
            model_name='tcgc_household',
            name='members',
            field=models.ManyToManyField(through='follow_app.tcgc_HouseholdMember', to='follow_app.member'),
        ),
        migrations.DeleteModel(
            name='TcgcHousehold',
        ),
        migrations.DeleteModel(
            name='TcgcHouseholdMember',
        ),
    ]
