# Generated by Django 5.0.6 on 2024-07-11 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_app', '0011_remove_tcgchouseholdmember_household_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcgc_household',
            name='head',
        ),
        migrations.RemoveField(
            model_name='tcgc_household',
            name='members',
        ),
        migrations.RemoveField(
            model_name='tcgc_householdmember',
            name='household',
        ),
        migrations.RemoveField(
            model_name='tcgc_householdmember',
            name='member',
        ),
        migrations.AddField(
            model_name='household',
            name='head',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='household_head', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='tcgc_Household',
        ),
        migrations.DeleteModel(
            name='tcgc_HouseholdMember',
        ),
    ]
