# Generated by Django 5.0.6 on 2024-07-12 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow_app', '0013_alter_household_head'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='head',
        ),
    ]
