# Generated by Django 5.0.6 on 2024-07-12 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_app', '0014_remove_household_head'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='members',
        ),
        migrations.RemoveField(
            model_name='householdmember',
            name='member',
        ),
        migrations.AddField(
            model_name='household',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='households', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='follow_app.household'),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='position',
            field=models.CharField(max_length=255),
        ),
    ]
