# Generated by Django 5.0.6 on 2024-07-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_app', '0015_remove_household_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='user',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
