# Generated by Django 5.0.6 on 2024-07-12 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow_app', '0016_alter_household_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='household',
            old_name='user',
            new_name='username',
        ),
    ]
