# Generated by Django 5.0.6 on 2024-07-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_app', '0017_rename_user_household_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
