# Generated by Django 5.0.6 on 2024-07-13 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_app', '0018_alter_household_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='householdmember',
            name='name',
        ),
        migrations.AddField(
            model_name='householdmember',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='follow_app.member'),
            preserve_default=False,
        ),
    ]
