# Generated by Django 5.0.6 on 2024-07-13 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_app', '0020_remove_household_username_household_members_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='household_head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='household_head', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='is_head',
            field=models.BooleanField(default=False),
        ),
    ]
