# Generated by Django 5.0.6 on 2024-07-13 22:58

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow_app', '0026_rename_timestamp_message_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
