# Generated by Django 5.0.6 on 2024-07-16 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_app', '0030_household_past_username_alter_household_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='memberquery',
            name='past_username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='past_queries', to=settings.AUTH_USER_MODEL),
        ),
    ]
