# Generated by Django 5.0.6 on 2024-07-16 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow_app', '0031_memberquery_past_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='memberquery',
            name='reply_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memberquery',
            name='past_username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='past_queries', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
